hw06-solid
enotii/otus pull request #6
Opened 2024-02-24 20:56 UTC by enotii

2024-02-25 10:17 UTC, Anohin4 requested changes
Все очень грязно и с кучей нарушений ответственностей в классах

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/Main.java
> +        System.out.println("Мы приветствуем вас в своем банкомате, если вы не едите хвостики от хинкалей");
Абьюз, не по солиду

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/service/ATMService.java
> +    CashStorage<Cash> getStorage();
Немного странным выглядят параметры методов

Все методы кроме первого используют интерфейс Cash для обращения с деньгами
Реализация первового же метода оборачивает полученные аргументы в Cash
В чем цель такого первого метода?

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/service/ATMServiceImpl.java
> +        return cashManager.getCashStorage();
фактически все, что делает этот класс - вызывает методы кеш менеджера
Это антипаттерн, у тебя класс-прослойка без своего функционала фактически и не имеющий цели

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/test/java/ru/otus/controller/CashManagerTest.java
> +        assertEquals(e, ErrorMessageEnum.OPERATION_EXCEPTION.getMessage() + "takeCash");
для того, что ты тут проверяешь есть ассерт assertThrown

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/test/java/ru/otus/controller/CashManagerTest.java
> +        assertEquals(e, ErrorMessageEnum.OPERATION_EXCEPTION.getMessage() + "takeCash");
посмотрел тесты ниже, для них это тоже актуально

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/service/ATMServiceImpl.java
> +    public CashStorage<Cash> getStorage() {
Не очень понял зачем этот метод

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/model/CashStorage.java
> +public interface CashStorage<Cash> {
Зачем делать дженерик с захардоженным классом?

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/model/CashStorageImpl.java
> +public class CashStorageImpl implements CashStorage<Cash> {
Собственно тут про дженерик мы сразу и забываем, еще больше не понятно зачем оно

Все что делает этот класс - возвращает сет
То есть фактически это еще один класс-прослойка, у которого нет функционала вообще и если его удалить - ничего не поменяется в логике

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/model/CashStorageImpl.java
> +public class CashStorageImpl implements CashStorage<Cash> {
Если ты хочешь делать класс-хранилище денег, то он должен реализовывать какую-то логику 
Просто возвращать сет наружу - максимальный моветон, типа я вам хранилище отдал, а вы что хотите то и делайте

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/controller/CashManagerImpl.java
> +            throw new CashTransactionException("putCash");
Тексты ошибок абсолютно не информативны

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/model/CashImpl.java
> +    }
То есть фактически функционально хранилищем денег выступает класс Cash и реализация этого находится в методе equals
Ух

1) абсолютно неочевидно поведение класса equals и оно такое из-за того, что в него фактически запихнули логику хранилища денег. То есть пачка денег с 50ю купюрами по 10 рублей у тебя равно сотне купюр с таким же номиналом
Если ты такой код встретишь в продакшене - ты будешь очень долго орать при дебаге
2) как следствие прошлого - нарушение принципа единой ответственности, Класс одновременно реализует и  логику хранилища и реалиует функционал "кучка денег", так как он является моделью для общения с пользователем

3) такая реализация фактически запрещает складывать в хэшмапу или хэш сет, потому тогда будет фейрверк в логике

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/controller/CashManagerImpl.java
> +            if (c.equals(cash)) {
Эта логика работает исколючительно из-за того как у тебя реализован метод equals в Cash,  так как если мы сделаем реализацию этоко метода через ломбоковскую аннотацию @equals - логика полностью ломается
То есть твой этот класс знает о том, как конкретно реализован метод equals в кеше 
Это нарушает прицип подстановки Лисков и все рухнет к чертям, если метод будет реализован так, как обычно ждешь от equals

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/controller/CashManagerImpl.java
> +    }
У нас есть два сета, класса которые обычно используют для того, что бы не итерироваться по ним

И мы используем вложенную итерацию одного сета в другом из-за того, что мы не можем просто использовать метод get
А не можем из-за того, что и как мы реализовали в cash

2024-02-25 10:17 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/controller/CashManagerImpl.java
> +    private Cash takeBanknotes(Cash c, int amount) {
Этот метод существует из-за того, что класс Cash вроде как и хранилище, а вроде как и нет 
Этот метод долженен быть именно в хранилище

2024-02-25 10:22 UTC, enotii commented on HW06-SOLID/src/main/java/ru/otus/Main.java
> +        System.out.println("Мы приветствуем вас в своем банкомате, если вы не едите хвостики от хинкалей");
отклонено

2024-03-12 17:21 UTC, Anohin4 requested changes
Есть ряд мелких замечаний, их поправить и норм

2024-03-12 17:21 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/service/CashManagerImpl.java
> +        return resultCash;
Мы создаем new ArrayList, переменную которого мы тут же переопределяем на строчке 34 и возвращаем фактически то, что нам вернул метод 
Предложил бы так 
       
        if (cashStorage.getTotalBalance() < sum) {
            throw new CashTransactionException(ErrorMessageEnum.NO_MONEY.getMessage());
        } 
        return cashStorage.takeCash(sum);

результат тот же, читать проще

2024-03-12 17:21 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/service/CashManagerImpl.java
> +    }
Этот метод нигде не используется, зачем он нам?

2024-03-12 17:21 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/service/CashManagerImpl.java
> +    CashStorage cashStorage;
В классе нет логики возврата текущего баланса, что требуется по задаче

2024-03-12 17:21 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/storage/CashStorageImpl.java
> +        }
у мапы есть метод возврата сета ключей, им можно вот это заменить

2024-03-12 17:21 UTC, Anohin4 commented on HW06-SOLID/src/main/java/ru/otus/storage/CashStorageImpl.java
> +        Collections.sort(sortedList,  Collections.reverseOrder((Comparator.comparing(CashNominalEnum::getNominal))));
 Вот эта строчка читается очень тяжело

2024-03-12 18:34 UTC, enotii commented on HW06-SOLID/src/main/java/ru/otus/service/CashManagerImpl.java
> +    }
добавила для наглядности тестов

2024-03-12 18:40 UTC, enotii commented on HW06-SOLID/src/main/java/ru/otus/service/CashManagerImpl.java
> +        return resultCash;
поправила

2024-03-12 18:50 UTC, enotii commented on HW06-SOLID/src/main/java/ru/otus/storage/CashStorageImpl.java
> +        }
поправила

2024-03-12 18:50 UTC, enotii commented on HW06-SOLID/src/main/java/ru/otus/storage/CashStorageImpl.java
> +        Collections.sort(sortedList,  Collections.reverseOrder((Comparator.comparing(CashNominalEnum::getNominal))));
поправила

2024-03-20 18:21 UTC, merged